### ISSUE TITLE
Create Magnum template vanish

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#236] opened 2022-12-21 14:06 UTC
I try to create a Magnum template like described in https://github.com/vexxhost/atmosphere/blob/main/docs/coe.md, I get the message `Request to create cluster template k8s-v1.25.3 accepted` but when I do a list `openstack coe cluster template list` I do not get any templates back.

Also when I look in the DB I do not get any databases back:
```
mysql> use magnum
mysql> select * from cluster_template;
Empty set (0.00 sec)

```

I get this issue on the hardware cluster (deployed with Atmosphere) but also on a development cluster deployed with Atmosphere.

**Comment by okozachenko1203** [comment] 2023-01-10 06:18
I couldn't reproduce this issue on my side.
Could you share the magnum logs when you attempt template creation?

**Comment by mpiscaer** [comment] 2023-01-11 16:06
I have created a log of the creating of the template.


[magnum_create_template.txt](https://github.com/vexxhost/atmosphere/files/10394036/magnum_create_template.txt)

**Comment by mnaser** [comment] 2023-01-16 02:11
Can you check the health of your Persona XtraDB cluster?

```
oslo_messaging.rpc.client.RemoteError: Remote error: TimeoutError QueuePool limit of size 5 overflow 50 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
```

It looks like it's quite unhappy.

**Comment by mnaser** [comment] 2023-01-20 18:46
Closing this since it seems like this was because of a bad Magnum image build.

**Closed by mnaser** 2023-01-20 18:46 UTC
