### ISSUE TITLE
openvswitch deployment error

### ISSUE THREAD

**Issue by thywyn** [vexxhost/atmosphere#174] opened 2022-11-15 15:59 UTC
Yesterday pulled most recent version of master and I am having issues with the openvswitch deployment:
`$ kubectl logs openvswitch-847h8 -n openstack -c init
Entrypoint ERROR: 2022/11/15 15:36:23 customresource.go:37: Unable to unmarshal variable DEPENDENCY_CUSTOM_RESOURCE with value : unexpected end of JSON input
Entrypoint WARNING: 2022/11/15 15:36:23 kubernetes-entrypoint.go:34: COMMAND env is empty`

**Comment by mnaser** [comment] 2022-11-15 16:15
this seems to be a duplicate of https://github.com/vexxhost/atmosphere/issues/174

**Closed by mnaser** 2022-11-15 16:15 UTC
