### ISSUE TITLE
Possible to create duplicate subnet names in public network

### ISSUE THREAD

**Issue by m49sdgn230n** [vexxhost/atmosphere#399] opened 2023-05-02 19:56 UTC
Using the member role, a user is able to create additional subnets in the shared public network. They are unable to create an overlapping subnet, but they can define a unique CIDR range and give it the same name. This is then shown across all domains when creating an instance or attaching an interface:

![image](https://user-images.githubusercontent.com/33265662/235770031-15f0283e-6431-4977-a95b-46765392f8e9.png)

If a subnet with a duplicate name is created, it will block future redeployments:

`failed: [controller] (item=[{'external': True, 'mtu_size': 1500, 'name': 'public', 'port_security_enabled': True, 'provider_network_type': 'flat', 'provider_physical_network': 'external', 'shared': True}, {'allocation_pool_start': 'x.x.x.x', 'allocation_pool_end': 'x.x.x.x', 'cidr': 'x.x.x.x/22', 'dns_nameservers': ['x.x.x.x', 'x.x.x.x'], 'enable_dhcp': True, 'gateway_ip': 'x.x.x.x', 'name': 'public-subnet'}]) => {"ansible_loop_var": "item", "attempts": 60, "changed": false, "extra_data": {"data": null, "details": "None", "response": "None"}, "item": [{"external": true, "mtu_size": 1500, "name": "public", "port_security_enabled": true, "provider_network_type": "flat", "provider_physical_network": "external", "shared": true}, {"allocation_pool_end": "x.x.x.x", "allocation_pool_start": "x.x.x.x", "cidr": "x.x.x.x/22", "dns_nameservers": ["x.x.x.x", "x.x.x.x"], "enable_dhcp": true, "gateway_ip": "x.x.x.x", "name": "public-subnet"}], "msg": "Multiple matches found for public-subnet"}`

**Comment by okozachenko1203** [comment] 2023-05-15 12:23
This issue is caused by the changes outside of the atmosphere.
In this case, we have 2 options
- add a custom policy to disallow the subnet creation with a specific name(the name used in atmosphere)
- Or use a special name which is not used for users normally
@mnaser  what do you think?

**Comment by okozachenko1203** [comment] 2023-05-15 14:51
> @okozachenko1203 i think the issue here is that it's the possiblity of creating a subnet on a network you don't own (in this a case, a member role can create the subnet on the public network which they dont own)...
> 
> maybe you can try and see if you can replicate it first @okozachenko1203 ?

@mnaser  yes, a member of admin project can create a subnet in the public network

**Comment by okozachenko1203** [comment] 2023-05-15 15:07
It is a bit strange. Default policy for `create_subnet` action is 
```
#"create_subnet": "(rule:admin_only) or (role:member and project_id:%(project_id)s) or rule:network_owner"
```
And in atmoephere, we never override the policies
```
neutron@neutron-server-78bbcfcbc7-g8cjj:/etc/neutron$ cat policy.yaml 
{}
```

**Comment by okozachenko1203** [comment] 2023-05-15 16:03
https://review.opendev.org/c/openstack/openstack-helm/+/883168

**Comment by okozachenko1203** [comment] 2023-06-06 13:58
@m49sdgn230n We are trying to find the reason why this new default rule is not working. Btw, that rule definition itself is logically positive.
I think you can define the override rule for create_subnet  using legacy rule as a workaround for now
```
neutron_helm_values:
  conf:
    policy:
      "create_subnet": "rule:admin_or_network_owner"
```

**Comment by okozachenko1203** [comment] 2023-06-13 16:21
I was able to reproduce the same issue in Devstack `stable/zed`. I reported to the neutron project team.

**Comment by okozachenko1203** [comment] 2023-06-23 06:37
The fix has been merged into master branch. https://review.opendev.org/c/openstack/neutron/+/886231

Here is the patch for cherry-pick to stable/zed https://review.opendev.org/c/openstack/neutron/+/886680

**Comment by ricolin** [comment] 2023-06-28 07:01
https://review.opendev.org/c/openstack/neutron/+/886680 just merged
Now only matters to release https://review.opendev.org/c/openstack/releases/+/887138
and update Atmosphere with new image

**Comment by mnaser** [comment] 2023-07-01 03:52
@okozachenko1203 @ricolin awesome progress here :)

**Closed** 2023-07-03 17:49 UTC
Labels: priority: critical
