### ISSUE TITLE
New OVS image fails in octavia-health-manager-nic-init 

### ISSUE THREAD

**Issue by thywyn** [vexxhost/atmosphere#665] opened 2023-10-20 20:20 UTC
With the newer images of OVS they do not include iptables which Octavia's health manager uses in it's init containers.  Please recompile with iptables added.

```
kubectl -n openstack logs --tail 1000 octavia-health-manager-default-qfxkq -c octavia-health-manager-nic-init
++ cat /tmp/pod-shared/HM_PORT_ID
...
...
+ ovs-vsctl --may-exist add-port br-int o-hm0 -- set Interface o-hm0 type=internal -- set Interface o-hm0 external-ids:iface-status=active -- set Interface o-hm0 external-ids:attached-mac=<MAC> -- set Interface o-hm0 external-ids:iface-id=c529cc9d-d2f9-4da8-8dc3-e3b159667de8 -- set Interface o-hm0 external-ids:skip_cleanup=true
+ ip link set dev o-hm0 address <MAC>
+ iptables -I INPUT -i o-hm0 -p udp --dport 5555 -j ACCEPT
/tmp/octavia-health-manager-nic-init.sh: line 21: iptables: command not found
```

**Comment by mnaser** [comment] 2023-10-20 20:24
Duplicate of https://github.com/vexxhost/atmosphere/issues/659

**Closed** 2023-10-20 20:24 UTC
